# This is a basic workflow to help you get started with Actions

name: My-Action-Basic
# Global ENV list
env:
  APP_NAME:  "MyFlas"
  PACKAGE_NAME: "Flask-Deploy-Version-${{ github.sha }}" # ENV that github provides (calling using ${{ env_name }} - syntax)
  

# Controls when the action will run. 
on:

  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs called "my-test" and "my-build"
  my-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:      
        # Print defined ENV variables
      - name: Execute few commands TEST
        run: |
          echo "Test env."
          echo "Application name: ${{ env.APP_NAME }}" 
        # Clone current repo to the container
      - name: Git clone repository
        uses: actions/checkout@v1
        
      - name: Current folder list
        run: ls -la


  my-build:
    runs-on: ubuntu-latest
    needs: my-test # This job only will be run after job my-test is complete
    
    steps:
      - name: Execute few commands BUILD
        # Print defined ENV variables
        run: |
          echo "Build env."
          echo "Package name: ${{ env.PACKAGE_NAME }}"
      - name: Check if AWS CLI installed by default
        run: aws --version
      - name: Check if archivators are installed
        run: | 
          zip --help
          tar --help






