# This is a basic workflow to help you get started with Actions

name: My-Action-Basic

# Controls when the action will run. 
on:

  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo "Test Step"          
       


  my-build:
    runs-on: ubuntu-latest
    needs: my-test # This job only will be run after job my-test is complete
    
    steps:
      - name: Print build
        run: echo "Build Step"
